### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by benmerckx** [back2dos/foxhole#2]
I've been trying to setup a basic test of tink_http, but didn't get far. Then I figured I try using foxhole first since it should be easier to get going. I'm running into the same problem though. I set up your example like this:

``` haxe
class Main {
  static function respond() {
    Sys.println('This works');
  }
  static function main() {
    foxhole.Web.run({
      handler: respond,
      watch: true
    });
  }
}
```

This compiles but does not seem to keep running. Output is this:

```
Main.hx:24: count 0 -> Worker:ROOT_LOOP/worker#0
Main.hx:24: count 1 -> Worker:ROOT_LOOP/worker#1
(...)
Main.hx:24: count 28 -> Worker:ROOT_LOOP/worker#3
Main.hx:24: count 29 -> Worker:ROOT_LOOP/worker#4
```

After that the process stops and no requests are served. I've tried without watch:true and --run Forever as well, but that just seems to run the process indefinitely.

**Comment by back2dos** [comment]
Sorry, my bad. I had mistakenly published tink_runloop with a `Main.hx` I used for local testing. Please `haxelib update tink_runloop` and it should work.

**Comment by benmerckx** [comment]
Thanks, this works :)
